### ISSUE TITLE
Gerenciamento de Custos

### ISSUE THREAD

**Issue by beatriz-paz** [EngenhariaTelecom/ProjetoIntegradorII#5]

**Comment by BudaKin** [comment]
https://docs.google.com/spreadsheets/d/1-UW7b5fhXtSBrWcRQ6u3cpoNKt1qkEaIeaDszFaZENM/edit?usp=sharing

link da planilha

**Comment by BudaKin** [comment]
finalizado: https://docs.google.com/spreadsheets/d/1-UW7b5fhXtSBrWcRQ6u3cpoNKt1qkEaIeaDszFaZENM/edit?usp=sharing
